name: Bug Report
description: Report a bug for STATS+ (Fabric only)
title: "[Bug]: "
labels: [bug]
type: bug

body:
  - type: markdown
    attributes:
      value: |
        STATS+ is Fabric-only.
        Other server-side mods are not supported.
        Client-side mods are allowed.

  - type: checkboxes
    id: ci
    attributes:
      label: Compatibility Check
      options:
        - label: Using Fabric Loader
        - label: No other server-side mods installed
        - label: Client-side mods only (if any)
        - label: Using latest STATS+ version

  - type: input
    id: statsplus_version
    attributes:
      label: STATS+ Version
    validations:
      required: true

  - type: input
    id: minecraft_version
    attributes:
      label: Minecraft Version
    validations:
      required: true

  - type: input
    id: fabric_version
    attributes:
      label: Fabric Loader Version
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Singleplayer
        - Integrated Server
        - Dedicated Server
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      render: shell
